### ISSUE TITLE
RealESRGAN 处理图片提示成功但无输出文件, 处理自带视频demo报错

### ISSUE THREAD

**Issue by MoeGrid** [Baiyuetribe/paper2gui#1]
## 处理图片提示成功无输出文件截图（两个版本）
![bug](https://user-images.githubusercontent.com/8309713/167358776-2a7f7e94-6f07-40eb-a36f-f5f2e1375aa8.png)

## 处理自带demo视频失败截图
![bug1](https://user-images.githubusercontent.com/8309713/167358790-c4fe85f8-23f5-4898-8715-49db57f838c5.png)

## 环境信息

CPU: AMD Ryzen 9 5900HX

显卡: NVDIA RTX 3060 Laptop

系统: Windows 11 专业版 21H2

**Comment by Baiyuetribe** [comment]
本地沙箱环境测试没问题，要不你加这个群给你发一个测试版，方便传递具体报错内容。389853598

**Comment by MoeGrid** [comment]
报错内容我已经分析了，是我显卡驱动不是最新，不支持vulkan，已经可以了，但是我觉得应该把报错内容显示出来而不是显示成功

**Comment by Baiyuetribe** [comment]
ok,因为接触vulkan才不久，以为没啥兼容性问题，就完全省略了报错内容

**Comment by Baiyuetribe** [comment]
鉴于旧程序有硬盘杀手的称号，我们重写了基于纯内存、不消耗硬盘空间的sdk,并加入了处理进度。
![](https://github.com/Baiyuetribe/paper2gui/raw/main/docs/images/realESRGAN_RAM.png)
可以试试新的内版本：[RealESRGAN-GUI-RAM](https://github.com/Baiyuetribe/paper2gui/blob/main/Video%20Super%20Resolution/RealESRGAN-GUI-RAM.md)
