### ISSUE TITLE
是否会考虑更换许可

### ISSUE THREAD

**Issue by LenorEric** [Baiyuetribe/paper2gui#10]
软件被用以收费的二次分发是十分困扰的行为
考虑到软件被套壳并用以提供收费在线服务的可能
请问在可以预见的未来，您们是否会考虑将许可证换为 AGPL 等将提供在线服务也视为分发行为的许可证？

**Comment by Baiyuetribe** [comment]
这块不是很熟，稍微懂点技术的应该可以看到我使用的所有技术来源，包括核心的AI模型都是开源代码。
受限于国内付费软件环境并不乐观，应该很少有嵌套收费的吧？
当然我不是很懂这块，如果你建议更改协议，请再次回复一下

**Comment by LenorEric** [comment]
您好，我提出建议是基于以下常见的三种情况：
1. 第三方开发者尽管也是懂技术的人，但是由于他们懒得自己做 GUI 封装，所以选择了基于您的软件进行二次开发，在其中加入强制收费（例如每进行一次转换需要扫他们的支付二维码等）的功能。这样他们几乎什么都没做，却从中获利。
2. 第三方不懂技术，但是把您的软件放在淘宝等网站上售卖，并以此获利。许多不了解技术的人没有其他得到您的软件的途径，因此只得从这些商家处购买。
3. 第三方不怎么懂技术，但是在淘宝上提供相关服务（例如补帧），并使用您的免费软件来完成操作后，交付转换后的成品。

使用 GPL 协议可以避免 (1) (2) 种情况的出现，而使用 AGPL 协议可以避免上述三种情况的出现。
尽管第三方依然可以忽视/违反您使用的协议，但如果您无意中发现了存在这种情况，且恰好对方盈利额不是个小数目。考虑到您的软件完全合法，您如果愿意的话可以进行起诉并要求对方进行赔偿，并得到相当于其违法所得数目的赔偿。
此外，我有观察到您提到的部分模型采用 GPL 授权。我不清楚这部分模型是否包含在了项目中，但是如果包含了，那么此项目是不可以采用 MIT 授权的，而仅可以采用 GPL 等相兼容的协议。

当然，具体怎么样还是取决于您最后的选择。

**Comment by Baiyuetribe** [comment]
从目前开源的方式而言，仅发布了打包好的可执行文件，相关源码因为横跨多个编程语言或技术，都在软件关于页面写了参考链接。既然已发布，至于别人二次收费那是别人本事，毕竟会编程的只是少部分人，能被大众广泛使用也是软件开发者的福音，未来的付费走向可能是做一个独立的、统一最优模型、功能最全的订阅制软件。
因此，暂无意愿变更，变更协议当前几乎没啥实质意义

**Comment by LenorEric** [comment]
好滴
