### ISSUE TITLE
微软语音能否加入azure订阅的语音支持

### ISSUE THREAD

**Issue by cloudoshk** [Baiyuetribe/paper2gui#11]
azure 中国的订阅
https://chinaeast2.api.cognitive.azure.cn/sts/v1.0/issuetoken

**Comment by Baiyuetribe** [comment]
看不到链接内容，微软不就一个通用api吗？最好发相关开发或对接文档，否则单个连接不知道是啥

**Comment by cloudoshk** [comment]
> 

微软云分国内和国际
国内:azure.cn
国际:azure.com

国内支持文档：
https://docs.azure.cn/zh-cn/cognitive-services/speech-service/text-to-speech
语音服务定价
https://www.azure.cn/pricing/details/cognitive-services/

理论上更换链接就可以，技术一样的。

如果需要azure账户支持，我可以提供密钥。

**Comment by Baiyuetribe** [comment]
接入实现差不多，但是该接口仅限企业级用户使用，等以后有空再折腾了

**Comment by zhengda-skinny** [comment]
> 
这个页面应该都是免费的
https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/language-support?tabs=speechtotext#text-to-speech

**Comment by Baiyuetribe** [comment]
由于v2.2.4新增azure和Edge两个接口，此接口后续不再追加。更多细节参见https://xiaobaituai.com/changelog
