### ISSUE TITLE
超分时GPU合成视频失败

### ISSUE THREAD

**Issue by knaxLFea** [Baiyuetribe/paper2gui#12]
使用超分时，到最后一步提示GPU合成视频失败，使用CPU合成。过了几小时电脑自动重启，输出的视频打不开

**Comment by Baiyuetribe** [comment]
具体哪个软件？

**Comment by knaxLFea** [comment]
> 具体哪个软件？
![image](https://user-images.githubusercontent.com/64300648/180750712-cf273e01-3573-470c-af17-e9eca7150805.png)

**Comment by Baiyuetribe** [comment]
最直观的办法，使用软件名称带[🔥]的，都是最先进的算法，一些古老的问题就没有

**Comment by ColinZeb** [comment]
RealESRGAN-GUI智能视频超分工具RAM版
GPU 3050Ti 
日志卡在这：
The overscoring operation has been manually terminated
FPS: inf, Time: 0, Task: 20/181, => 11.050%
Mission coming to an end

另一台电脑1080 卡在Mission coming to an end

**Comment by Baiyuetribe** [comment]
@ColinZeb 我又仔细理了下运行逻辑，并未发现可复现的故障，`The overscoring operation has been manually terminated`代表你手动终止了任务。`Mission coming to an end`代表程序即将执行完毕。如果我这边无法复现，你的问题将永远得不到解决

**Comment by ColinZeb** [comment]
@Baiyuetribe 我是下载后解压运行，选的视频文件就是自带的示例文件。进度条在20% ，日志最后一条是Mission coming to an end，一开始我以为正常的，结果半个小时后还是20%，除了提供日志我还能做什么呢。另外解决不解决都没关系，我只是试用一下

**Comment by Baiyuetribe** [comment]
@ColinZeb  无法复现，将无法修复。根据现有的描述，无从入手

**Comment by Baiyuetribe** [comment]
已修复，更多细节请参考[变更日志](https://github.com/Baiyuetribe/paper2gui/releases/tag/%E5%B0%8F%E7%99%BD%E5%85%94AI_v2.2.0)
