### ISSUE TITLE
请问能加入命令行模式吗

### ISSUE THREAD

**Issue by heiheiheibj** [Baiyuetribe/paper2gui#13]
你好，请问能加入命令行模式吗？
这样在一些其它程序中，就可以通过命令行方式，指定输入、输出文件，并取得log日志信息
谢谢

**Comment by Baiyuetribe** [comment]
除了线上colab外，现有的GUI应用里，命令行模式不会加入，如需命令行请参考相关资料自制一下

**Comment by heiheiheibj** [comment]
谢谢
