### ISSUE TITLE
在 MODNet-GUI智能视频抠图工具 中，选择的文件路径过长时，会被图片遮挡，无法单击运行

### ISSUE THREAD

**Issue by Lunsit** [Baiyuetribe/paper2gui#14]
![image](https://user-images.githubusercontent.com/61680403/181870777-a799db0a-65d7-443b-bbee-7a1062a8dc71.png)

**Comment by Baiyuetribe** [comment]
软件窗口可以放大缩小，窗口也可以随意缩放
