### ISSUE TITLE
AI视频超分 - RealESRGAN(Video Super-resolution)无法使用

### ISSUE THREAD

**Issue by knaxLFea** [Baiyuetribe/paper2gui#15]
当进度条到达20%时，GPU占用变为0

**Comment by Baiyuetribe** [comment]
请确保你的显卡驱动是最新版本，或者自查一下是否支持vulkan.

**Comment by knaxLFea** [comment]
> 请确保你的显卡驱动是最新版本，或者自查一下是否支持vulkan.

显卡驱动是这周内更新的，应该是最新版本。显卡是30系，肯定支持vulkan

**Comment by Baiyuetribe** [comment]
那就奇怪了，开发环境为20系。这种情况如果没法复现，我也无能为力啊

**Comment by knaxLFea** [comment]
> 那就奇怪了，开发环境为20系。这种情况如果没法复现，我也无能为力啊

建议加个log功能

**Comment by Baiyuetribe** [comment]
程序运行，底部不就有详细log日志吗？

**Comment by knaxLFea** [comment]
> 程序运行，底部不就有详细log日志吗？

那些log只能看出当前所处的步骤哪一步，而看不出问题所在。对了补充一个情况，图片可以正常超分，但是视频不行

**Comment by Baiyuetribe** [comment]
日志也不发，也不截个图啥的。。。等其他人反馈再说吧

**Comment by knaxLFea** [comment]
> 日志也不发，也不截个图啥的。。。等其他人反馈再说吧

Mission coming to an end
start video matting
4
Start super-resolution
[STEP-1/3]Audio extraction successful ---> Time consuming: 741.2613ms
[STEP-0/3]:Video Info: Duration: 00:00:36.08, start: 0.000000, bitrate: 2208 kb/s\r\n Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 720x984 [SAR 1:1 DAR 30:41], 2078 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
Total time consumed: 27.0668202s
【END】===>Output files: D:\好图\QQ图片20220527194740_RealESRGAN_4X_0731180517.png
【Mission completed】Time consuming：27.0663079s
start image task
--------------------------------
The overscoring operation has been manually terminated
Mission coming to an end
start video matting
2
Start super-resolution
[STEP-1/3]Audio extraction successful ---> Time consuming: 752.6137ms
[STEP-0/3]:Video Info: Duration: 00:00:36.08, start: 0.000000, bitrate: 2208 kb/s\r\n Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 720x984 [SAR 1:1 DAR 30:41], 2078 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
some output logs
![image](https://user-images.githubusercontent.com/64300648/182021614-210de2da-7892-46ed-9716-a412ef7603fb.png)

**Comment by knaxLFea** [comment]
Start super-resolution
[STEP-1/3]Audio extraction successful ---> Time consuming: 752.6137ms
[STEP-0/3]:Video Info: Duration: 00:00:36.08, start: 0.000000, bitrate: 2208 kb/s\r\n Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 720x984 [SAR 1:1 DAR 30:41], 2078 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
some output logs
![image](https://user-images.githubusercontent.com/64300648/182021671-470e6e2c-f628-4b0c-8db2-d7929aaac0a7.png)

**Comment by Baiyuetribe** [comment]
早就该这样做了，大致知道了，等我消息

**Comment by Baiyuetribe** [comment]
你这个问题需要在你设备上调试一下，我这边暂无30系显卡，无法复现，请加QQ2894049053

**Comment by Sostay** [comment]
我这边也是永远卡在20%……，图片可以正常处理，视频不行

**Comment by Sostay** [comment]
> 我这边也是永远卡在20%……，图片可以正常处理，视频不行

试了一下 用旧版可以正常工作~

**Comment by Baiyuetribe** [comment]
试试刚刚发布的小白兔AI ，已自适应GPU性能，低配笔电应该不会再有问题了
![image](https://user-images.githubusercontent.com/43716063/185085279-3736b18b-e325-4d20-93cb-af3d010505c4.png)
下载地址跟以前一样

**Comment by knaxLFea** [comment]
> 试试刚刚发布的小白兔AI ，已自适应GPU性能，低配笔电应该不会再有问题了 ![image](https://user-images.githubusercontent.com/43716063/185085279-3736b18b-e325-4d20-93cb-af3d010505c4.png) 下载地址跟以前一样

nice！

**Comment by Baiyuetribe** [comment]
#30 已解决
