### ISSUE TITLE
这就是中国的码农?

### ISSUE THREAD

**Issue by flarejune** [Baiyuetribe/paper2gui#16]
其实就是个GUI壳而已,话说这种打着程序员名号的打包狗,能不能不要继续侮辱中国的程序员了.做个外壳套用别人的东西,就不敢说一声或者贴个Thanks名单?

**Comment by Baiyuetribe** [comment]
你眼瞎吗？不论GitHub还是软件内的关于页面，都有参考来源

**Comment by physihan** [comment]
> 

有能耐你也做一个，在这当键盘侠干嘛

**Comment by zhuhongjie** [comment]
你可真是个有人生没人养的贱畜啊
