### ISSUE TITLE
按钮被遮挡，无法使用……

### ISSUE THREAD

**Issue by Sostay** [Baiyuetribe/paper2gui#17]
<img width="768" alt="Snipaste_2022-08-10_17-39-09" src="https://user-images.githubusercontent.com/6897274/183869580-b633272d-fce1-40c3-a2bd-d27ecb8cf004.png">
试用了几个不同 功能的软件，都有类似的情况
我的电脑分辨率是4K

**Comment by Baiyuetribe** [comment]
右上角可放大窗口，边框也可以随意放大缩小
