### ISSUE TITLE
建议视频输出可自定义 FFmpeg 参数

### ISSUE THREAD

**Issue by zzh4n** [Baiyuetribe/paper2gui#2]
测试 900MB/8min/25fps 的视频 RIFE 插帧到 120 帧压制完成文件大小只有 160MB ，画面非常糊全是马赛克。

建议像 OBS 一样增加 FFmpeg 自定义输出参数。或者至少默认输出 `-vcodec hevc_nvenc -preset slow -qp 21` / `-vcodec libx265 -preset slow -crf 23` 的水平。电脑跑了一天结果体验还不如原视频真的心态爆炸。

同时催一下 RAM 版本的 RIFE 和 DAIN，硬盘真的遭不住。

**Comment by Baiyuetribe** [comment]
哈哈，旧应用硬盘杀手名不虚传。RIFE内存版正在做

**Comment by Baiyuetribe** [comment]
rife-gui内存版已发布，告别两次硬盘读写，速度比旧版提升30%以上，唯一遗憾的是暂时没有搞定自定义帧率，只能在现有基础上把帧率放大2/3/4倍

**Comment by zzh4n** [comment]
> rife-gui内存版已发布，告别两次硬盘读写，速度比旧版提升30%以上，唯一遗憾的是暂时没有搞定自定义帧率，只能在现有基础上把帧率放大2/3/4倍

请问视频输出参数调整有考虑吗 QAQ

**Comment by Baiyuetribe** [comment]
内存模式下，没有两次硬盘读写，全程都是内存中无损处理图片，输出也是h264最佳模式。如果加入ffmpeg的那些参数，仅仅是组合一下就有几十种，对普通人更不友好，现实情况只需要最好的，因此不予考虑自定义参数。
