### ISSUE TITLE
视频超分工具执行到2%就出错了

### ISSUE THREAD

**Issue by hunsui** [Baiyuetribe/paper2gui#20]
这里是输出日志
输出视频提取信息失败，疑似不支持文件
几个工具都这样提示，原视频是AVI的老视频800*600的，就想弄清晰一点，还有WMV的也是这样提示。

**Comment by Baiyuetribe** [comment]
临时解决办法，格式转换一下： [下载mencoder.exe](http://oss.netfarm.it/mplayer-win32.php)， 在window命令行下使用：
 mencoder in.avi -ovc raw -vf format=i420 -o out.avi
