### ISSUE TITLE
未找到OCR识别工具

### ISSUE THREAD

**Issue by ZCyueternal** [Baiyuetribe/paper2gui#21]
OCR识别工具没有找到，请问是否还未添加。

**Comment by Baiyuetribe** [comment]
是的，OCR核心技术没问题，但是暂时没有想好具体展现形式，比如截屏或图片识别？单次看起来没啥意思。目前计划中将这块OCR用于视频字幕识别。如有比较实际的用途，欢迎提交具体想法

**Comment by aiastia** [comment]
天若orc 已经有了

>

**Comment by Vainycos** [comment]
期待OCR识别功能

**Comment by Baiyuetribe** [comment]
刚刚发布的2.1.3版已完成OCR批量识别功能
下载地址：[小白兔AI](https://download.fastgit.org/Baiyuetribe/paper2gui/releases/download/Published/XiaoBaituAI_windows.zip)
[更多变更日志，可点此查看](https://xiaobaituai.com/changelog)

**Comment by Vainycos** [comment]
thanks,已收到！



***@***.***
 
发件人： 佰阅
发送时间： 2022-08-29 21:21
收件人： Baiyuetribe/paper2gui
抄送： Vainycos; Comment
主题： Re: [Baiyuetribe/paper2gui] 未找到OCR识别工具 (Issue #21)
刚刚发布的2.1.3版已完成OCR批量识别功能
下载地址：小白兔AI
更多变更日志，可点此查看
