### ISSUE TITLE
版主为啥不做一个整合版本，这样方便好多咯

### ISSUE THREAD

**Issue by liyang-it** [Baiyuetribe/paper2gui#22]

**Comment by Baiyuetribe** [comment]
嗯，其实已经快做好了，停更一个月就是在做这个事情。这几天会发布的

**Comment by liyang-it** [comment]
那个视频抠图，可以设置背景嘛

**Comment by jamescvbn** [comment]
感谢作者！！

既然这样，那我晚点再下载[狗头]

建议做一个launcher，默认不带工具（或带少数几个火爆且小的工具），点击某项自动下载（可以设置从GitHub还是国内网站）。这样使用门槛更低一些。

**Comment by Baiyuetribe** [comment]
> 那个视频抠图，可以设置背景嘛

好主意，已设想了几种场景，后续将集成近来

**Comment by Baiyuetribe** [comment]
统一的APP 做好了，起了个中文名“小白兔AI”, 下载地址跟以前一样
![image](https://user-images.githubusercontent.com/43716063/185086786-f618a50c-68dd-4321-bac8-180e7321f49f.png)

**Comment by jiaoting** [comment]
额，然后开始收费了。。。

**Comment by Baiyuetribe** [comment]
@jiaoting 靠爱发电做不久的，付费只是为了做了更好，况且一顿外卖钱就可以用一年，很便宜了

**Comment by jiaoting** [comment]
建议增加写文推荐、或者推荐安装获取积分，兑换会员，这样也能起到一定的推广

**Comment by itoukou1** [comment]
但是利用开源收费是不是不太好？

**Comment by itoukou1** [comment]
> @jiaoting 靠爱发电做不久的，付费只是为了做了更好，况且一顿外卖钱就可以用一年，很便宜了


但是利用开源项目收费是不是不太好？

**Comment by Baiyuetribe** [comment]
@itoukou1  别人可以，我为什么不可以呢？svfi、waifu2x都是非常贵的，而且核心代码都不是他们自己写的。AI文献太多了，不做收费转换只能沦为纸上paper。不支持付费也可以，反正我已写了20多个免费的。

**Comment by itoukou1** [comment]
> waifu2x

wafu2x是开源的。不是收费的，谢谢。是日本的一个项目，在线地址http://waifu2x.udp.jp/

**Comment by itoukou1** [comment]
> @itoukou1 别人可以，我为什么不可以呢？svfi、waifu2x都是非常贵的，而且核心代码都不是他们自己写的。AI文献太多了，不做收费转换只能沦为纸上paper。不支持付费也可以，反正我已写了20多个免费的。

wafu2x是开源的。不是收费的，谢谢。是日本的一个项目，在线地址http://waifu2x.udp.jp/

**Comment by jamescvbn** [comment]
收费没问题。作者要明确收费的部分是对这些算法的整合和工具化，用户为提升效率付费。

原算法的LICENSE按说应该包含在这工具中。具体不是很懂，作者 @Baiyuetribe 可以了解下，避免法律风险。

**Comment by itoukou1** [comment]
> 收费没问题。作者要明确收费的部分是对这些算法的整合和工具化，用户为提升效率付费。
> 
> 原算法的LICENSE按说应该包含在这工具中。具体不是很懂，作者 @Baiyuetribe 可以了解下，避免法律风险。

有部分算法是不支持商用的
