### ISSUE TITLE
ai 图片抠图有问题

### ISSUE THREAD

**Issue by aiastia** [Baiyuetribe/paper2gui#23]
![demo_rvm_blue](https://user-images.githubusercontent.com/19776350/184561243-252b99fe-e28b-4f11-9dfd-ab1098b872d2.png)
![demo_rvm_dark](https://user-images.githubusercontent.com/19776350/184561244-61d081e4-e68e-4b70-8511-920dcf53128f.png)
![demo_rvm_green](https://user-images.githubusercontent.com/19776350/184561245-f3e54ac8-942e-4dc7-8b2d-6d24ff6d06eb.png)
![demo_rvm_red](https://user-images.githubusercontent.com/19776350/184561232-02e32be3-17c0-4304-9f83-811ecf8072d9.png)
![demo_rvm_white](https://user-images.githubusercontent.com/19776350/184561236-2fa8190c-5210-4036-a467-2b4957a6bbc9.png)
![demo_rvm_alpha](https://user-images.githubusercontent.com/19776350/184561239-2e462579-1bbf-4899-aa88-17146b7aff18.png)
![demo_rvm_alpha_rvm_alpha](https://user-images.githubusercontent.com/19776350/184561241-c792b721-004f-44ff-85ff-667e24028dfc.png)

默认图片扣的是这样的

**Comment by Baiyuetribe** [comment]
设备GPU信息报下

**Comment by aiastia** [comment]
gt 730
