### ISSUE TITLE
能否追加语音转文字

### ISSUE THREAD

**Issue by aiastia** [Baiyuetribe/paper2gui#26]
感觉语音转文字日常用的也多

**Comment by Baiyuetribe** [comment]
已在计划中
![image](https://user-images.githubusercontent.com/43716063/185086271-dba45b10-82a3-4403-a394-edc3b1b081e1.png)

**Comment by Baiyuetribe** [comment]
该功能已有进展，离线语音识别、视频字幕生成等，近期会上线

**Comment by Baiyuetribe** [comment]
已实现，参见[变更日志](https://xiaobaituai.com/changelog)
