### ISSUE TITLE
RIFE-GUI(RAM) 转换之后的视频无法跳进度播放

### ISSUE THREAD

**Issue by JoeZhangYN** [Baiyuetribe/paper2gui#27]
视频经过转换后效果和Topaz video enhance 的效果差不多，但是Topaz转换出来的视频可以跳进度播放，RIFE-GUI(RAM) 转换出来的视频无法跳进度，鼠标点后面的进度直接重新开始播放。

**Comment by JoeZhangYN** [comment]
另：rife-ncnn-vulkan 更新了 20220728 望更新

**Comment by Baiyuetribe** [comment]
rife4.2 需要nihui大佬出面转换，ram版已经不是调用rife-ncnn-vulkan实现的，她哪个是批量处理图片的，我设计的是处理视频的。
你可以试试刚刚发布的统一APP 小白兔AI
![image](https://user-images.githubusercontent.com/43716063/185090046-31caa115-fed1-4d56-a2ed-7e36be3eb0d7.png)
下载地址跟以前一样

**Comment by JoeZhangYN** [comment]
两个模型都测试过了，好像出了点BUG，转换过程消失了，最终也无文件输出。  

Total time consumed: 3.8131239s  
[Task finished]  --->  Output files: C:\Users\JoeZhang\Downloads\Compressed\抠图测试_小白兔AI_0817180328.mp4  
[STEP-3/3] Audio merge complete ---> time consuming: 1.4709854s  
[STEP-2/3]Video processing complete ---> time consuming: 661.1572ms  
Usage0: see https://xiaobaituai.com  
Start processing video  
[STEP-1/3]Audio extraction successful ---> Time consuming: 1.6799735s  
[STEP-0/3]:Video Info: Duration: 00:00:14.73, start: 0.000000, bitrate: 3455 kb/s\r\n  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 2607 kb/s, 23.98 fps, 24 tbr, 12288 tbn (default)  
[Info:] AI Engine version: 2.0.1  

Total time consumed: 3.7512648s  
[Task finished]  --->  Output files: C:\Users\JoeZhang\Downloads\Compressed\抠图测试_小白兔AI_0817180443.mp4  
[STEP-3/3] Audio merge complete ---> time consuming: 1.4237441s  
[STEP-2/3]Video processing complete ---> time consuming: 658.8422ms  
Usage0: see https://xiaobaituai.com  
Start processing video  
[STEP-1/3]Audio extraction successful ---> Time consuming: 1.6676707s  
[STEP-0/3]:Video Info: Duration: 00:00:14.73, start: 0.000000, bitrate: 3455 kb/s\r\n  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 2607 kb/s, 23.98 fps, 24 tbr, 12288 tbn (default)  
[Info:] AI Engine version: 2.0.1

**Comment by Baiyuetribe** [comment]
好奇怪，即便是我的沙箱环境，也没有复现该bug，等其他人反馈看看
