### ISSUE TITLE
低配笔电运行视频类超分/补帧/抠图可能仍存在问题

### ISSUE THREAD

**Issue by 2435206827** [Baiyuetribe/paper2gui#30]
视频补帧，两个模型到5%会卡住，CPU/GPU占用降低至约为零
Log：
Input fps:30.00, Output fps:60.00,origin_count:391,target_count:781
start video frame interpolation
Start processing video
[STEP-1/3] Audio Extraction Success ---> Time Consuming: 782.1588ms
[STEP-0/3] Video Info: Duration: 00:00:13.03, start: 0.000000, bitrate: 853 kb/s\r\n  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 360x360 [SAR 1:1 DAR 1:1], 610 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
[Info:] AI Engine Version: 2.1.0

动漫超分，RealCugan-Pro在并发手动调整至3以下可用，而RealESRGAN也会卡在Start peocessing video
Log：
Start processing video
[STEP-1/3] Audio Extraction Success ---> Time Consuming: 630.032ms
[STEP-0/3] Video Info: Duration: 00:00:13.03, start: 0.000000, bitrate: 853 kb/s\r\n Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 360x360 [SAR 1:1 DAR 1:1], 610 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
[Info:] AI Engine Version: 2.1.0

人像抠图可以正常开始，但是运行到中途会突然卡住，不再继续

视频类功能已经换多个视频验证，其余功能使用无问题

笔电配置：
CPU：AMD A6-9220 RADEON R4, 5 COMPUTE CORES 2C+3G 
GPU 0：AMD Radeon(TM) R4 Graphics
GPU 1：AMD Radeon (TM) R5 M330

**Comment by Baiyuetribe** [comment]
感谢反馈，这是由于GPU自适应匹配算法还存在问题(尤其是笔记本设备上)，只有`RealCugan-Pro`模型上放弃了自适应匹配改为手动模式。当然自动化还是优先考虑的，已有几个思路，待验证，一旦突破就会更新的。 另外超分补帧都是强GPU需求的，推荐台式机显卡进行加速推理。

**Comment by 2435206827** [comment]
好的，谢谢！
&nbsp;


LDDMiao
***@***.***

NNSZ
18277711467


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月24日(星期三) 中午1:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Baiyuetribe/paper2gui] 低配笔电运行视频类超分/补帧/抠图可能仍存在问题 (Issue #30)





 
感谢反馈，这是由于GPU自适应匹配算法还存在问题(尤其是笔记本设备上)，只有RealCugan-Pro模型上放弃了自适应匹配改为手动模式。当然自动化还是优先考虑的，已有几个思路，待验证，一旦突破就会更新的。 另外超分补帧都是强GPU需求的，推荐台式机显卡进行加速推理。

**Comment by Baiyuetribe** [comment]
今日已更新手动控制并发数，可根据自己显卡体制手动调整，这样就不会异常退出了。重写下载并安装就能自动完成升级
![image](https://user-images.githubusercontent.com/43716063/186420470-5cc0f8a8-01a1-4308-bae2-14dde6b091b3.png)

**Comment by 2435206827** [comment]
已经可以了！感谢修复。
另外，视频补帧在Start processing video时存在进度条显示的小BUG
&nbsp;


LDDMiao
***@***.***

NNSZ
18277711467


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月24日(星期三) 晚上8:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Baiyuetribe/paper2gui] 低配笔电运行视频类超分/补帧/抠图可能仍存在问题 (Issue #30)





 
今日已更新手动控制并发数，可根据自己显卡体制手动调整，这样就不会异常退出了。重写下载并安装就能自动完成升级

**Comment by Baiyuetribe** [comment]
刚刚已修复 v2.1.2
更多变更日志[参考这里](https://xiaobaituai.com/changelog)
