### ISSUE TITLE
特性请求：批量文件选择

### ISSUE THREAD

**Issue by qryl** [Baiyuetribe/paper2gui#33]
辛苦了Baiyuetribe大大，感谢整合了那么多那么好用的功能。

目前在使用modnet时， 发现无法批量选择多个文件或文件夹。
请问能否劳烦您加入批量选择这一个功能？

非常感谢！

**Comment by Baiyuetribe** [comment]
加批量处理的话，就跟现在的OCR识别一样了，需要加进度条，下次更新可以考虑加入

**Comment by Baiyuetribe** [comment]
刚刚发布的v2.3.0已实现图片和视频批量处理，详情参见[变更日志](https://xiaobaituai.com/changelog)
