### ISSUE TITLE
超分和人像抠图功能会卡在95%

### ISSUE THREAD

**Issue by jsjk01** [Baiyuetribe/paper2gui#36]
见图片，任务运行时候GPU会拉满，然后95%就停了，进度条也不动了，看任务管理器也熄火了
![image](https://user-images.githubusercontent.com/39907479/187819815-6ae39bf1-940c-4c2a-9c5b-9d668a1ff783.png)

任务管理器看也没有占用资源（看着像是任务停止了
![image](https://user-images.githubusercontent.com/39907479/187819960-37a02cf1-23ef-48cc-b39a-d5fda1503764.png)

**Comment by Baiyuetribe** [comment]
报下cpu和GPU信息，如果gpu显存小于8G，请尝试降低并发数，并观察任务栏gpu利用率和显存占用，理想状态为利用率满载且不爆显存

**Comment by jsjk01** [comment]
CPU：Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz
GPU 0：Intel(R) UHD Graphics
	驱动程序版本:	30.0.101.1368
	驱动程序日期:	2022/1/27
	DirectX 版本:	12 (FL 12.1)
	专用 GPU 内存：4.0 GB
	共享 GPU 内存：7.9 GB
	GPU 内存：7.9 GB

GPU 1：NVIDIA GeForce GTX 1650 Ti
	驱动程序版本：30.0.15.1289
	驱动程序日期：2022/5/14
	DirectX 版本：12 (FL 12.1)
	专用 GPU 内存：0.9/4.0 GB
	共享 GPU 内存：7.9 GB
	GPU 内存：11.9 GB

测试视频大小：1.04M

用单独版本（非聚合版）可以正常使用；使用聚合版并发数8没有爆内存，卡95%，降低并发数也是95%
聚合版-并发数8
![1662021104904](https://user-images.githubusercontent.com/39907479/187869878-49795b7d-d5c1-4cc5-9afa-b37ace45dfbf.jpg)
![1662021066742](https://user-images.githubusercontent.com/39907479/187869952-92483326-7c51-4607-b1ae-006df76c2c35.jpg)
5分钟后
![image](https://user-images.githubusercontent.com/39907479/187870225-e0f396b0-0f46-4438-96e7-4a0a09c0509c.png)
![image](https://user-images.githubusercontent.com/39907479/187870291-db6ff7b0-5e9d-4374-9687-1d98d0b4492c.png)

---
聚合版-并发数2
![image](https://user-images.githubusercontent.com/39907479/187870847-220e7ad8-17dc-4227-874d-f5c191470fc5.png)
![1662021370913](https://user-images.githubusercontent.com/39907479/187870871-224c0657-097a-4d5d-a863-5085f646c412.jpg)
5分钟后
![image](https://user-images.githubusercontent.com/39907479/187872258-1f198b3a-f9e3-4fc6-91c8-65325a6dd295.png)
![image](https://user-images.githubusercontent.com/39907479/187872219-42461a64-8bd1-4a14-a3a5-ba1c5fb155ef.png)

**Comment by Baiyuetribe** [comment]
卡在95%说明AI处理已完成，卡在音频合并上，就很奇怪，要不附上你的视频文件，1MB文件在issue里可以上传。另外我提供的测试视频也卡在95%吗？

**Comment by jsjk01** [comment]
用提供的视频也会。
![image](https://user-images.githubusercontent.com/39907479/187891854-1a1d88b7-02f8-4498-9afe-7e047dae337c.png)

下面是软件内输出
```log
Average FPS: 6.82862
Total elapsed time: 26.5061s
Total frames: 181
FPS: 3.54, Time: 282.7117, Task: 180/181, => 89.503%
Mission coming to an end
FPS: 0.91, Time: 1097.5819, Task: 160/181, => 79.558%
FPS: 0.89, Time: 1129.7561, Task: 140/181, => 69.613%
FPS: 1.73, Time: 578.7024, Task: 120/181, => 59.669%
FPS: 0.87, Time: 1153.7758, Task: 100/181, => 49.724%
FPS: 1.00, Time: 1002.9448, Task: 80/181, => 39.779%
FPS: 1.74, Time: 575.484, Task: 60/181, => 29.834%
FPS: 0.89, Time: 1126.7866, Task: 40/181, => 19.890%
FPS: 0.88, Time: 1142.0741, Task: 20/181, => 9.945%
Start processing video
[STEP-1/3] Audio Extraction Success ---> Time Consuming: 92.2333ms
[STEP-0/3] Video Info: Duration: 00:00:07.55, start: 0.000000, bitrate: 627 kb/s\r\n  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 640x480 [SAR 1:1 DAR 4:3], 303 kb/s, 23.98 fps, 23.98 tbr, 19184 tbn (default)
[Info:] AI Engine Version: 2.1.3
```

**Comment by jsjk01** [comment]
人像抠图 - 聚合版
![image](https://user-images.githubusercontent.com/39907479/187892697-38653484-c7c5-4611-91d0-1b9fe53f4751.png)

人像抠图 - MobileNetV2-GUI智能视频抠图工具
![image](https://user-images.githubusercontent.com/39907479/187892902-cb05fe14-9d86-43e6-815a-67ab51e498b3.png)
![image](https://user-images.githubusercontent.com/39907479/187892946-9b231f3c-c90b-4ece-8929-57d39a07f8aa.png)

**Comment by Baiyuetribe** [comment]
https://github.com/Baiyuetribe/paper2gui/releases/download/Published/AI-test.zip
测试下这个文件，可能无法解决问题，但会具体显示异常信息，记得截图右下角弹窗

**Comment by jsjk01** [comment]
下面是报错的截图
![image](https://user-images.githubusercontent.com/39907479/188038306-1ebabe5d-ec82-4c4d-90ca-64f55a70d9b5.png)

**Comment by jsjk01** [comment]
> 这回应该可以解决了，测试下新的，完成后给个反馈 https://github.com/Baiyuetribe/paper2gui/releases/download/Published/AI-test.zip
一样的报错信息
![image](https://user-images.githubusercontent.com/39907479/188051046-825f7d34-28f2-4544-ba49-384508e1bcda.png)

**Comment by Baiyuetribe** [comment]
这个应该还是之前的版本，可能是版本升级导致的，重新下载这个 https://github.com/Baiyuetribe/paper2gui/releases/download/Published/AI-test.zip
确保首页版本号2.1.5.然后再进行测试

**Comment by jsjk01** [comment]
> 这个应该还是之前的版本，可能是版本升级导致的，重新下载这个 https://github.com/Baiyuetribe/paper2gui/releases/download/Published/AI-test.zip 确保首页右下角版本号2.1.5.然后再进行测试

版本2.1.5（另，个人中心进不去了现在
![image](https://user-images.githubusercontent.com/39907479/188072040-bb4eeaa6-24d2-4893-828e-45391fc3ffee.png)

![image](https://user-images.githubusercontent.com/39907479/188071992-9b631e9a-20ea-4b0a-a78c-bdb2013c7c52.png)

**Comment by Baiyuetribe** [comment]
建议卸载重装，感觉都不像是最新版该有的样子，异常内容已被程序拦截，为何还会出现？实在想不通

**Comment by Baiyuetribe** [comment]
感谢反馈，终于找到原因了，个人中心也已修复，进度卡95%应该不会再发生了。 v2.1.4 https://github.com/Baiyuetribe/paper2gui/releases/download/Published/XiaoBaituAI_windows.zip

**Comment by jsjk01** [comment]
> 感谢反馈，终于找到原因了，个人中心也已修复，进度卡95%应该不会再发生了。 v2.1.4 https://github.com/Baiyuetribe/paper2gui/releases/download/Published/XiaoBaituAI_windows.zip

可以了
