### ISSUE TITLE
订阅涨钱了？？？

### ISSUE THREAD

**Issue by jiaoting** [Baiyuetribe/paper2gui#39]
涨钱了？？？？这才更新了一个版本。。。

**Comment by Baiyuetribe** [comment]
嗯，实际上已经迭代了9个版本。上涨是必然的，如果觉得太高，请反馈下大致可接受的价格，一定采纳

**Comment by majw88** [comment]
拿别人的东西攒巴攒巴自己设计个界面，然后卖这么贵，大写的服，这里面哪种技术是你原创的代码？

**Comment by Baiyuetribe** [comment]
@majw88 既然我可以做到，你也可以开源啊，没难度哪来的这么多star? 请先开源免费20个再来讨论

**Comment by Baiyuetribe** [comment]
根据反馈，AI聚合版定价现已大幅下降，请重新下载完成升级。聚合版提供7天免费试用和长期维护，目标是做成真正的生成力工具。如果不想付费，其他单独的20个应用完全免费，靠爱发电精力有限，不喜勿喷。
