### ISSUE TITLE
关于抖音火山神经网络引擎使用mac版，请教一下大佬们

### ISSUE THREAD

**Issue by rongttw** [Baiyuetribe/paper2gui#41]
下载解压出来。打开软件显示是文件，修改.dmg 安装也不支持 改.pkg安装也不可以 这个mac版本我该怎么去安装呢，请大佬们请教一下！！！非常感谢

**Comment by Baiyuetribe** [comment]
跟普通mac程序一样操作下，如果不支持就设置下权限。再不行就搞个Windows虚拟机

**Comment by rongttw** [comment]
> 跟普通mac程序一样操作下，如果不支持就设置下权限。再搞个Windows虚拟机就不行了

佰阅大大 我下载打开显示出来的是文稿文件。到底是哪里出了问题呀
