### ISSUE TITLE
TTS这块的Mac版本是否还未提供？

### ISSUE THREAD

**Issue by BlueToothpaste** [Baiyuetribe/paper2gui#45]
我看有人已经有提问了，下载下来改成.dmg和.pkg都无法打开文件

**Comment by Baiyuetribe** [comment]
开发时已通过测试，mac系统上软件已经是打包好的二进制可执行文件，只需赋予执行权限，就能打开了。如果搞不定请使用Windows虚拟机

**Comment by BlueToothpaste** [comment]
打开终端
chmod a+x 微软神经网络语音合成工具Mac版
