### ISSUE TITLE
大大

### ISSUE THREAD

**Issue by Stardust911** [Baiyuetribe/paper2gui#47]
非常感谢制作，绑了很多忙。有两个建议：
一是可不可以批量进行超分，这样更方便，
二是参考其他UI设置一个可以拖拽文件到此处更方便。

**Comment by Baiyuetribe** [comment]
1. 批处理功能新版已实现，详情参考[v2.3.0变更日志](https://xiaobaituai.com/changelog)
2. 默认输出将自动打开文件夹，不再设置自定义目录
3. 聚合版使用realcugan_pro模型，推理异常已特殊备注，请使用esr
