### ISSUE TITLE
报错 0xc0000135 

### ISSUE THREAD

**Issue by pedoc** [Baiyuetribe/paper2gui#49]
系统：Win10 22H2 x64
最开始正常，但是第一次点击开始下载模型的时候太慢，手动点了取消后，重启程序再点开始，就始终是这个错误，进度条也不会移动

![image](https://user-images.githubusercontent.com/6604230/203037210-6205e0a5-e2ee-4a40-90dd-661d36bf143f.png)

**Comment by Baiyuetribe** [comment]
哦，进入c盘，用户目录，找到`.xbt_sb_novel`删除该文件夹，然后就相当于初始环境了，开始安装，大概等十几分钟。之后就可以正常使用了

**Comment by pedoc** [comment]
感谢说明，现在能下载但还是会提示这个错误。从文件大小看应该已经下载完成了

![image](https://user-images.githubusercontent.com/6604230/203061100-44bd66ca-5f37-4306-95ad-a2bf1dcd64c2.png)

**Comment by pedoc** [comment]
好像和内存关系也不大，我扩展内存后还是一样的问题。
会不会是缺少某些环境？我这是一个全新的Win10，至安装了一次vs2022.

这个错误码是推理模型时下级依赖抛出的吗？还是上层封装抛出的？如果是下级依赖抛出的那的确不好定位原因，就是个黑盒子。

![image](https://user-images.githubusercontent.com/6604230/203201469-bab91382-6b6b-48c6-b15f-1b004d9b011d.png)

已安装软件列表
![image](https://user-images.githubusercontent.com/6604230/203201809-16dfef9b-21bb-493f-b68e-9771e87c4b6f.png)

**Comment by nihui** [comment]
0xc0000135 通常缺少一些 dll  :eyes:

**Comment by Baiyuetribe** [comment]
@pedoc 如果是dll文件的问题，进入程序目录后，双击exe文件，如果缺少dll会弹出提示，正常情况下只会窗口闪现一下
![image](https://user-images.githubusercontent.com/43716063/203214146-dd178400-818e-4ea5-a0eb-306e3258b31d.png)

**Comment by pedoc** [comment]
还别说，真报缺少dll

![image](https://user-images.githubusercontent.com/6604230/203215945-af48466f-d64a-4668-bf82-9787c725e90d.png)

**Comment by pedoc** [comment]
我从其他机器拷贝了一个过去，现在看起来是正常。
感谢各位的支持

![image](https://user-images.githubusercontent.com/6604230/203216643-7616ddc4-f131-4271-8ca2-0f91524edd13.png)
![image](https://user-images.githubusercontent.com/6604230/203216679-4bb308a7-7e32-4614-b91a-205e30bd0c43.png)

**Comment by Baiyuetribe** [comment]
该问题仅在没有显卡的设备上必然出现，原因是上游ncnn库默认依赖此库，我已更新程序，后续不会再有该问题。
