### ISSUE TITLE
关于gpu报错

### ISSUE THREAD

**Issue by whghjyh** [Baiyuetribe/paper2gui#5]
之前一直运行的很好，今天不知道是不是由于禁用了一些服务，导致报错"请检查GPU是否存在"。虽然明白这是我自己的问题，但找了非常久没有任何头绪，所以还是想下次叨扰问下一般哪些情况会造成这一报错。（目前GPU工作正常，监视器显示有占用并且在工作）

**Comment by Baiyuetribe** [comment]
建议卸载现有的显卡驱动，重新安装最新的显卡驱动。如果问题仍然存在，请反馈具体软件。

**Comment by 3538532** [comment]
第一次使用这个软件，也出现这个提示，我的显卡是主板集成，具体型号是：Intel (R) HD Graphics 530，难道是不支持吗？

**Comment by Baiyuetribe** [comment]
@3538532 图形处理都非常依赖GPU配置，核显饶过它吧

**Comment by Zpolar** [comment]
电脑双显卡，切独显也是提示找GPU，可能电脑年头多了？
求大佬能不能适配一下，哪怕运行慢点呢~

**Comment by Baiyuetribe** [comment]
@Zpolar 与显卡相关的程序，都是调用了vulkan的API，一般只需要升级显卡驱动为对应的最新版本，都可以支持。
可以找到自己显卡对应的官方网站，查看并安装一下最新驱动：
- Intel: https://downloadcenter.intel.com/product/80939/Graphics-Drivers
- AMD: https://www.amd.com/en/support
- NVIDIA: https://www.nvidia.com/Download/index.aspx

**Comment by Cuuuuuu0** [comment]
我也出现了类似情况，无法检测到GPU，具体软件是realcugan-gui和realESRgan-gui，我重装了显卡驱动但是无效，大佬麻烦看看程序是不是出了啥问题

**Comment by Baiyuetribe** [comment]
@Cuuuuuu0 如果是首次使用就这样，那无解。

**Comment by Cuuuuuu0** [comment]
@Baiyuetribe 我用了一个周差不多后才出现的

**Comment by whghjyh** [comment]
在C盘temp里删掉对应的文件夹就行了，一般为“realesrgan-sdk”类似的格式，找不到用everything搜索sdk然后删掉相应的就会解决。
