### ISSUE TITLE
StableDiffusion有没有GPU版本？

### ISSUE THREAD

**Issue by 863zq** [Baiyuetribe/paper2gui#50]
如题，StableDiffusion在CPU上面跑太慢了，请问有没有GPU版本呢？

**Comment by Baiyuetribe** [comment]
会有的，预计年后，敬请关注

**Comment by Baiyuetribe** [comment]
已完成，现在起开GPU加速显著。详情参见[变更日志](https://xiaobaituai.com/changelog)
