### ISSUE TITLE
AI绘画的模型文件被封了

### ISSUE THREAD

**Issue by xvzhenduo** [Baiyuetribe/paper2gui#51]
AI绘画的模型文件被封了，希望能说一下模型文件是release中的哪几个
![image](https://user-images.githubusercontent.com/74353173/203221846-ddb502c7-2fb5-4c86-a06b-040edad299bf.png)

**Comment by Baiyuetribe** [comment]
linux二进制文件在阿里云默认会被封。其实软件内置了下载渠道，首次等个十几分钟就好了。如果非要手动下载，还可以从如下渠道下载(仅下载bin后缀的文件)
- [谷歌](https://drive.google.com/drive/folders/1myB4uIQ2K5okl51XDbmYhetLF9rUyLZS)
- [百度网盘](https://pan.baidu.com/s/1kO8HtTZRcyDbzA32ZzafSQ?pwd=6666)

手动替换步骤，首次运行一遍程序里的开始，然后关闭窗口程序。然后覆盖存档如下三个文件即可
![image](https://user-images.githubusercontent.com/43716063/203223525-1ef95662-e9a9-412d-9c58-36a6b059714b.png)

**Comment by xvzhenduo** [comment]
谢谢
