### ISSUE TITLE
如何在StableDiffusionGUI中设置输出的图像大小？

### ISSUE THREAD

**Issue by chemicalfiber** [Baiyuetribe/paper2gui#53]
如题，StableDiffusionGUI让我感到非常惊艳，但是令我感到疑惑的是，现在它似乎只能生成512*512像素的图片，目前有没有方法能够调整输出图片的大小呢？还是说这个功能会在以后的版本中加入？

**Comment by Baiyuetribe** [comment]
@nihui 都想要16:9的横幅和竖幅模型

**Comment by Baiyuetribe** [comment]
@chemicalfiber 现已支持自定义动态尺寸啦，[点此查看更多日志](https://xiaobaituai.com/changelog)
![2023-1-23_11-11-50](https://user-images.githubusercontent.com/43716063/213969058-8c8d6410-e1f7-49d0-b2a6-917a27aaca94.png)
![2023-1-23_11-3-20](https://user-images.githubusercontent.com/43716063/213969098-433f39eb-7171-43c8-aae4-dd2de91a0b4c.png)
![2023-1-23_10-50-24](https://user-images.githubusercontent.com/43716063/213969137-ebcdf5b3-216d-4dc1-b52a-251dad8332fb.png)
