### ISSUE TITLE
经过超分辨率放大4倍的视频无法进行视频补帧？

### ISSUE THREAD

**Issue by shubenaipiaorou** [Baiyuetribe/paper2gui#57]
使用RealESRGAN-GUI(RAM)超分辨率放大2倍的视频可以进行视频补帧，但是生成的4倍视频不能进行视频补帧。我看任务进度那里应该是完成了但是没有输出，然后就弹出补帧失败了
![1A$H20M$ _Q9 SI H`TYTFT](https://user-images.githubusercontent.com/93376350/210263134-287d974e-7616-4039-8e8b-31ad1d7b5ac2.png)

**Comment by Baiyuetribe** [comment]
你截图的应用为早期实现，可能存在问题。[试下聚合版](https://xiaobaituai.com/)，
