### ISSUE TITLE
为减少歧义，请修改英文版 README

### ISSUE THREAD

**Issue by amakerlife** [Baiyuetribe/paper2gui#58]
中文版 README 并没有说这是免费的，事实上也不是免费的。但在 README_en 中却仍说是免费的。

https://github.com/Baiyuetribe/paper2gui/blob/46c02aad4fe9b0eba3ec49544d80e56e69957fd2/README_en.md?plain=1#L3

Google Translate

![image](https://user-images.githubusercontent.com/64350662/212604571-572992d9-2af6-4c62-ac7a-454a18a00179.png)

Deepl

![image](https://user-images.githubusercontent.com/64350662/212604628-2031d2bb-4297-4783-bce3-bb7e74226e69.png)

Baidu

![image](https://user-images.githubusercontent.com/64350662/212604646-94180bfc-8a27-423c-bde1-863f3824f551.png)

**Comment by Baiyuetribe** [comment]
![image](https://user-images.githubusercontent.com/43716063/212605316-a9f94a37-a636-491c-8f86-bfc27a7e1372.png)
all this is free. No conflict

**Comment by amakerlife** [comment]
> ![image](https://user-images.githubusercontent.com/43716063/212605316-a9f94a37-a636-491c-8f86-bfc27a7e1372.png) all this is free. No conflict

哦？貌似咱们的理解不一样，我认为这段话说的是 paper2gui（也就是小白兔 AI）是免费使用的，当然如果你坚信你的理解是正确的我也没办法

**Comment by amakerlife** [comment]
另外，stable-diffusion 的开源协议中明确表明 “You must give any Third Party recipients of the Model or Derivatives of the Model a copy of this License”，但我却没有在项目中找到这份协议，如果有，那请当我没说

https://github.com/CompVis/stable-diffusion/blob/21f890f9da3cfbeaba8e2ac3c425ee9e998d5229/LICENSE#L46

**Comment by amakerlife** [comment]
而且还很离谱的，用了这么多开源项目连个原项目仓库名或作者都不放？ @Baiyuetribe

**Comment by Baiyuetribe** [comment]
如何证明我没提供呢？你用都没用，好好看看软件里的关于页面，你说的啥都用

**Comment by Baiyuetribe** [comment]
以后用别人的项目，建议先用用再说，不要妄加评论。我开源三年多难道连门槛都没进入？
