### ISSUE TITLE
请问各种AI处理主要依赖于CPU还是GPU？另外voice colon 有推荐的项目吗？谢谢

### ISSUE THREAD

**Issue by lpalfreddd** [Baiyuetribe/paper2gui#59]

**Comment by Baiyuetribe** [comment]
![image](https://user-images.githubusercontent.com/43716063/218238726-28fb2caa-eb1b-40cb-bd7a-484266fe0e8e.png)

1. 以当前版本为例，除了语音合成、chatgpt等联网调用外，其余都依赖GPU。CPU在AI推理时很慢，但也有因为技术原因导致部分AI推理算子不支持GPU时，就依赖CPU运算，比如现有的AI绘画就是没有完整适配GPU计算。

2. voice colon暂不熟悉

**Comment by lpalfreddd** [comment]
谢谢回复






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Baiyuetribe/paper2gui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月11日(星期六) 中午12:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Baiyuetribe/paper2gui] 请问各种AI处理主要依赖于CPU还是GPU？另外voice colon 有推荐的项目吗？谢谢 (Issue #59)





 

  
 
以当前版本为例，除了语音合成、chatgpt等联网调用外，其余都依赖GPU。CPU在AI推理时很慢，但也有因为技术原因导致部分AI推理算子不支持GPU时，就依赖CPU运算，比如现有的AI绘画就是没有完整适配GPU计算。
 
 
 
voice colon暂不熟悉
