### ISSUE TITLE
Uninsatll卸载逻辑有严重问题

### ISSUE THREAD

**Issue by NaughtDZ** [Baiyuetribe/paper2gui#64]
不小心把程序安装在了根目录，直接双击uninstall卸载，好家伙，根目录里所有文件文件夹全删了，堪比格式化分区。。。

**Comment by Baiyuetribe** [comment]
一年多来，你是第一个有此骚操作的，😄，当前安装卸载是默认生成的，我查查资料看看能否避免此类问题

**Comment by Baiyuetribe** [comment]
感谢反馈，已找到解决办法，会在即将发布的3.0版实现

**Comment by Baiyuetribe** [comment]
已修复，参见[变更日志](https://xiaobaituai.com/changelog)
