### ISSUE TITLE
火山引擎语音合成异常，请检查appid和token

### ISSUE THREAD

**Issue by Thea-1026** [Baiyuetribe/paper2gui#65]
是不能用了吗

**Comment by Baiyuetribe** [comment]
独立APP，受火山引擎API的调整，已失效(包括火山自家的订阅接口)。可以尝试小白兔AI 3.0里的。另外也可以用微软edge或azure进行平替

**Comment by Thea-1026** [comment]
小白兔3.0也用不了欸，那火山引擎是整个都不能用了吗

**Comment by Baiyuetribe** [comment]
你不是没有登录呀？我刚测试正常。

**Comment by Thea-1026** [comment]
![image](https://user-images.githubusercontent.com/82020298/224695560-afc20c46-9694-41ee-90e2-5bdfe0642cac.png)
![image](https://user-images.githubusercontent.com/82020298/224695636-f0357f76-a9a1-44ca-9f8e-bc9120f77e1c.png)
微信扫码登录了诶

**Comment by Baiyuetribe** [comment]
我还是无法复现，等于无从下手。请加群远程看下497556961

**Comment by Baiyuetribe** [comment]
啊~~~ 从截图看出来了，你一直在拿旧版本跟我忽悠。请下载最新的版本https://github.com/Baiyuetribe/paper2gui/releases/download/Published/XBT_AI_Windows.exe
<img width="1446" alt="image" src="https://user-images.githubusercontent.com/43716063/224698250-d421e423-3477-4ba3-971c-c78e6e30f743.png">

**Comment by Thea-1026** [comment]
火山引擎好像又合成异常了？小白兔里面

**Comment by Baiyuetribe** [comment]
试用接口现在加了滑动验证，所以失效了；付费订阅渠道因火山api的调整也不稳定，你可以自行给火山客服反馈，说付费API调用后高频率报错：模型初始化失败。

**Comment by Thea-1026** [comment]
好的
