### ISSUE TITLE
没有mac intel芯片版本吗？

### ISSUE THREAD

**Issue by ekuwang** [Baiyuetribe/paper2gui#66]

**Comment by 0x0021** [comment]
+1

**Comment by Baiyuetribe** [comment]
抱歉，从技术角度来看，是可以实现这个想法的。然而，苹果公司已经全面转向ARM64处理器，且使用的体验非常优秀。例如，我的Mac Mini M2已经足以胜任所有的AI推理任务。如果要适配到Intel芯片的版本，可能只会剩下一小部分的AI功能可用，比如语音合成。并且在现阶段，我不想去尝试这个想法。

**Comment by Baiyuetribe** [comment]
想在inter尝鲜的，可以安装Windows虚拟机，然后使用Windows版的小白兔AI。
