### ISSUE TITLE
mac 微软语音合成报错 no such host

### ISSUE THREAD

**Issue by Moretai** [Baiyuetribe/paper2gui#67]
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/19297371/225811405-cfaa6834-7ce2-4fb9-a89f-a44b66309411.png">

**Comment by Baiyuetribe** [comment]
很明显，你填写的参数不正确；key和region填写错误

**Comment by Moretai** [comment]
@Baiyuetribe hey 作者你好。
这个是 azure 的图
<img width="854" alt="image" src="https://user-images.githubusercontent.com/19297371/225822016-9e470d9d-ed15-4d6a-8f20-6ddfaf1f3461.png">
这个是小白兔上的微软订阅
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/19297371/225822134-81de6ae6-afbd-4c0e-a851-3f6da9ea64af.png">
我有点困惑，是不是我在 azure 选的 Resources 错了吗？
真诚请教，🙏

**Comment by Baiyuetribe** [comment]
后面这张图看起来没有问题。难道也报错？
另外，微软语音Azure可以免填直接用，跟你现在接口是一样的，不过最好加上全局代理。
关于微软订阅接口开通，这里有一份以前的教程： https://github.com/Baiyuetribe/paper2gui/issues/7
