### ISSUE TITLE
大佬，能否写个获取微软key的教程

### ISSUE THREAD

**Issue by Reallywish** [Baiyuetribe/paper2gui#7]
如题 谢谢！

**Comment by Baiyuetribe** [comment]
教程很多，打开官网就能找到，没啥难度啊。
https://azure.microsoft.com/zh-cn/services/cognitive-services/text-to-speech
![image](https://user-images.githubusercontent.com/43716063/175284298-de19c151-c31e-4dd3-80f8-ac06ef7a1f05.png)

**Comment by Reallywish** [comment]
大佬秒回，太感谢了，已star，我在微软云上找了半天，搞半天是路走错了
