### ISSUE TITLE
使用AI变声器会导致软件闪退

### ISSUE THREAD

**Issue by yadinae** [Baiyuetribe/paper2gui#71]
无论是单文件还是批量处理，使用变声器的时候，如果源文件播放长度比较长，就可能导致软件闪退。
根据我的观察，软件应该是把源文件分片进行处理，但经常会出现其中一些片段处理失败，最后合并的时候，就会导致闪退。
这个问题希望处理一下。

**Comment by Baiyuetribe** [comment]
无法被修复，请提供可复现的音频。
另外最新版v3.0.2 如果已尝试最新版还是异常，请发异常文件音频到软件邮箱里。

**Comment by yadinae** [comment]
提示信息如下：

Infer [12/15] is Finished
some piece is failed
Infer [9/15] is Finished
Infer [7/15] is Finished
Infer [8/15] is Finished
Infer [6/15] is Finished
Infer [5/15] is Finished
Infer [4/15] is Finished
Infer [2/15] is Finished
Infer [1/15] is Finished
Infer [3/15] is Finished
Please wait a few minutes
Converted Audio Success

只要出现“some piece is failed”，就必然会闪退。

但同一个Mp3文件并非每次都会闪退，可能跟资源占用或网络通讯情况有关。

你们的邮箱是哪个？

**Comment by Baiyuetribe** [comment]
既然是网络问题，那就无法被修复。只能等以后出本地离线音色转换器了
