### ISSUE TITLE
微软语音合成无法使用

### ISSUE THREAD

**Issue by ucfxj** [Baiyuetribe/paper2gui#72]
输入文字，试听和合成都没有反映。使用的是最新版的小白兔AI

**Comment by Baiyuetribe** [comment]
无法复现。最新版v3.0.2 软件标题会有。另外反馈问题请截全图

**Comment by ucfxj** [comment]
> 无法复现。最新版v3.0.2 软件标题会有。另外反馈问题请截全图

最后登录账户才可以用合成语音。
不登陆账户，所有操作都没有反应
