### ISSUE TITLE
macbook pro（m1 pro）无法正常运行，报错：“小白兔AI”已损坏，无法打开。 你应该将它移到废纸篓。

### ISSUE THREAD

**Issue by 10xjzheng** [Baiyuetribe/paper2gui#74]
错误信息：“小白兔AI”已损坏，无法打开。 你应该将它移到废纸篓。
<img width="259" alt="image" src="https://github.com/Baiyuetribe/paper2gui/assets/8455705/c7fb8ad0-3502-4fea-8f69-e15356859e7c">

**Comment by Baiyuetribe** [comment]
请执行说明中的命令。
安装完毕后，在终端执行
`sudo xattr -rd com.apple.quarantine /Applications/小白兔AI.app`
