### ISSUE TITLE
MacBook pro(m1 pro)报错：“小白免 A1”已损坏，无法打开。你应该将它移到废纸篓。

### ISSUE THREAD

**Issue by 10xjzheng** [Baiyuetribe/paper2gui#75]
<img width="269" alt="企业微信截图_b7c6b76e-f88b-4a8d-8b83-cdf1eb1396dc" src="https://github.com/Baiyuetribe/paper2gui/assets/8455705/e273ca4a-adef-4c4a-8850-80bab20261b3">
“小白免 A1”已损坏，无法打开。你应该将它移到废纸篓。

**Comment by Baiyuetribe** [comment]
#74 same issue
