### ISSUE TITLE
希望app 支持 macbook pro intel版本 

### ISSUE THREAD

**Issue by Hyingerrr** [Baiyuetribe/paper2gui#76]
希望app 支持 MacBook Pro 老款 intel芯片版本

**Comment by Baiyuetribe** [comment]
建议搞个Windows虚拟机，然后使用Windows版本。我这边暂无相关设备来提供inter芯片支持

**Comment by Baiyuetribe** [comment]
3.2.2版本正式支持inter芯片。 参见官网：www.xiaobaituai.com
