### ISSUE TITLE
请问集成软件图像放大功能和那五个独立图像超分软件的运行日志在什么地方

### ISSUE THREAD

**Issue by skyBing** [Baiyuetribe/paper2gui#77]
请问集成软件图像放大功能和那五个独立图像超分软件的运行日志在什么地方？我用集成版放大图片时显示任务异常，用独立版放大图片没有输出的图片，只显示完成，我想看一下日志是不是我显存不够导致的，还是其它原因造成的

**Comment by Baiyuetribe** [comment]
新版昨日已修复，请从官网重新下载安装即可。[xiaobaituai.com](https://xiaobaituai.com/)
