### ISSUE TITLE
win 10，这个app经常闪退，但是任务管理器里还有进程，也不释放内存。

### ISSUE THREAD

**Issue by SMooxx** [Baiyuetribe/paper2gui#78]
如题，最新版的app，win 10，
机器配置如下：
![image](https://github.com/Baiyuetribe/paper2gui/assets/9960618/6556a76d-6fe4-4024-ab92-2c35efe8aa2e)

不知何故频繁崩溃，无法使用。

**Comment by Baiyuetribe** [comment]
已验证，在Windows上确实存在内存泄露。
由于代码内部机制问题，暂时无法排查到解决办法，临时解决办法，任务管理器手动终止相关进程。

另外，你的设备有两张显卡，建议在使用AI的时候，在设备管理器里禁用核显，防止软件调用核显。

**Comment by SMooxx** [comment]
另外，能不能升级一下啊。现在经常用到根据视频或音频生成字幕的功能，而这个功能最容易导致闪退，百思不得其解。无论什么配置的电脑，内存16G或者32G都无解。

**Comment by Baiyuetribe** [comment]
无法复现异常。请提相关功能的全局截图，从截图我能知道版本、系统环境、功能、及操作等信息
