### ISSUE TITLE
开发者好，可否添加文本文件切割功能

### ISSUE THREAD

**Issue by Mozillor** [Baiyuetribe/paper2gui#82]
超长文本例如小说，转mp3之前，先按指定字数分割成几个小txt文件，这样就能转成多个小的mp3了。

当然，如果能按照标题分割章节，就更完美了。

**Comment by Baiyuetribe** [comment]
技术上不难实现，难得是通用性适配。建议手动分割好文本，然后用小白兔进行批量合成。
