### ISSUE TITLE
支持linux了吗

### ISSUE THREAD

**Issue by Breach66** [Baiyuetribe/paper2gui#87]

**Comment by Baiyuetribe** [comment]
最新版3.2.2已从代码层面支持win、linux和mac的x64/arm64版本。由于发版计划，linux版后续补充。

**Comment by Baiyuetribe** [comment]
linux适配完毕，x64版和arm64版本。其中arm64架构由于上游vulkan暂无适配，因此arm64无GPU加速功能。
![image](https://github.com/user-attachments/assets/aeff4738-0c5d-4135-b892-e88630841af2)
具体下载地址：https://github.com/Baiyuetribe/paper2gui/releases/tag/Published
已知一些小bug：因linux的GTK暂不支持avif图片，界面图片会不显示；因音频解析在linux上报错GStreamer FDK AAC plugin is missing，所以音频模块的预览也是不工作

**Comment by Baiyuetribe** [comment]
从3.2.4起，Linux版宣布正式支持
![image](https://github.com/user-attachments/assets/c1e09a77-4c2c-4a9d-bb6f-26176400d210)
参见官网：[www.xiaobaituai.com](www.xiaobaituai.com)
