### ISSUE TITLE
这是假开源，装了软件还要注册帐号充钱才能用。

### ISSUE THREAD

**Issue by junfeidai** [Baiyuetribe/paper2gui#94]
卖货就卖货，别打着开源的幌子，非人哉。

**Comment by Baiyuetribe** [comment]
惭愧，本项目自2018年累计开源了20个独立的散装APP，但随着AI应用数量暴增，散装APP维护实在有心无力。
你仍然可以直接用旧应用，无需登录；也可以选择小白兔，里面的图片类十几个应用永久免费。
![image](https://github.com/user-attachments/assets/eb98cea5-711b-4748-ac11-d0dc6577142d)
